server:
  port: 80
  
spring:
  datasource:
    url: jdbc:postgresql://${P3_URL}/rev_overflow
    username: ${P3_ROLE}
    password: ${P3_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update